name: Build Docker Image and store in Jfrog
on:
  watch:
    branches:
      - main
jobs:
    build:
      name: push docker image to jfrog
      runs-on: linux-run01
      ##runs-on: karthik-win
      steps:
        - name: Checkout JAR
          uses: actions/checkout@v2
          
        - name: login to Jfrog
          uses: docker/login-action@v5.3.0
          with:
            registry: trialxdxact.jfrog.io
            username: karthiksekaran86
            password: Treasure#09
            
        - name: build the docker image and push
          uses: docker/build-push-action@v3.2.0
          with:
            push: true
            tags: trialxdxact.jfrog.io/test1-docker/ocp-test-1:1
