name: Build and Push Docker image 222

on:
  watch:
    branches:
      - main  # Triggers the workflow on push to the main branch  
jobs:
  build:
    runs-on: linux-run01

    steps:
    - name: Checkout repository
      run: |
       ls -ltra
       pwd
       echo "ABC"
           
