name: Manual Input
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
    build:
      name: manual entry test
      runs-on: linux-run01
      steps:
        - name: first step to print parameter
          id: build-docker-image
          run: |
            ls -la && echo "Hello"
