# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package and Commit 1

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: linux-run01
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 2
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven 2
      run: mvn -B package --file pom.xml

    - name: Make target directory 3
      run: git remote set-url origin https://username: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@github.com/karthiksekaran86/ocp-gitaction-1.git && git config --global user.name "karthiksekaran86" && git config --global user.email "karthiksekaran86mail@gmail.com" && git add . && git status && git commit -am "yml commit" && git push origin HEAD
      
